In [1]:
import numpy as np

In [2]:
english_score =E= np.array([55,89,76,65,48,70])
math_score =M= np.array([60,85,60,68,55,60])
chinese_score =C= np.array([65,90,82,72,66,77])

In [3]:
#1. 有多少學生英文成績比數學成績高？
np.greater(E, M)

array([False,  True,  True, False, False,  True])

In [17]:
a=np.array([False,  True,  True, False, False,  True])
print(np.sum(a==1))

3


In [19]:
#2. 是否全班同學最高分都是國文？
np.greater(C, E)

array([ True,  True,  True,  True,  True,  True])

In [20]:
np.greater(C, M)

array([ True,  True,  True,  True,  True,  True])

In [22]:
x=np.array([ True,  True,  True,  True,  True,  True])
y=np.array([ True,  True,  True,  True,  True,  True])
np.logical_and(x, y)

array([ True,  True,  True,  True,  True,  True])