In [1]:
import numpy as np

In [2]:
english_score =E= np.array([55,89,76,65,48,70])
math_score =M= np.array([60,85,60,68,np.nan,60])
chinese_score =C= np.array([65,90,82,72,66,77])

In [3]:
#1.請計算各科成績平均
np.arraymean=(np.mean(E),np.nanmean(M), np.mean(C))
np.arraymean

(67.16666666666667, 66.6, 75.33333333333333)

In [4]:
#1.請計算各科成績最大值、最小值
np.arrayE=(np.max(E),np.min(E))
np.arrayE

(89, 48)

In [5]:
np.arrayM=(np.nanmax(M),np.nanmin(M))
np.arrayM

(85.0, 60.0)

In [6]:
np.arrayC=(np.max(C),np.min(C))
np.arrayC

(90, 65)

In [7]:
#1.請計算各科成績標準差
np.arraystd=(np.std(E),np.nanstd(M),np.std(C))
np.arraystd

(13.433995020924426, 9.707728879609279, 8.825468196582484)

In [14]:
#2.第五位同學補考數學後成績為 55，請計算補考後數學成績平均、最大值、最小值、標準差？
math_score =M= np.array([60,85,60,68,np.nan,60])
where_are_nan = np.isnan(M)
M[where_are_nan] = 55
print(M)

[60. 85. 60. 68. 55. 60.]


In [15]:
np.arrayM=(np.mean(M),np.max(M),np.min(M),np.std(M))
np.arrayM

(64.66666666666667, 85.0, 55.0, 9.860132971832694)

In [17]:
#3.用補考後資料找出與國文成績相關係數最高的學科？
np.corrcoef(C,E)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])

In [18]:
np.corrcoef(C,M)

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

In [20]:
0.97792828>0.74056803

True