In [1]:
import numpy as np

In [2]:
array1 = np.array([[10, 8], [3, 5]])
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
B = np.linalg.inv(array1 )
B

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [3]:
A = array1 = np.array([[10, 8], [3, 5]])
B = np.linalg.inv(array1 )

In [4]:
C = np.dot(A, B)
C

array([[1., 0.],
       [0., 1.]])

In [5]:
#arrayC符合單位矩陣In的重要性質為： AIn = A 且InB = B，故為單位矩陣

In [6]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(C)

In [7]:
# eigenvalues特徵值
w

array([1., 1.])

In [8]:
# eigenvector特徵向量
v

array([[1., 0.],
       [0., 1.]])

In [9]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(C)

In [10]:
u

array([[0., 1.],
       [1., 0.]])

In [11]:
s

array([1., 1.])

In [12]:
vh

array([[0., 1.],
       [1., 0.]])